---
- name: Start Agent and Download Parcel
  hosts: all
  become: yes
  tasks:



    - name: Start Cloudera Manager agent
      ansible.builtin.shell:
        cmd: systemctl start cloudera-scm-agent 
      tags:
        - startagent

    - name: Download Parcel
      get_url:
        url: https://archive.cloudera.com/cdh7/7.1.7/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976-bionic.parcel
        dest: /opt/cloudera/parcel-repo/
        mode: '0644'
      tags:
        - parcel


    - name: Download Parcel .sha1
      get_url:
        url: https://archive.cloudera.com/cdh7/7.1.7/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976-bionic.parcel.sha1
        dest: /opt/cloudera/parcel-repo/
        mode: '0644'
      tags:
        - parcel.sha1

    - name: Download Parcel .sha256
      get_url:
        url: https://archive.cloudera.com/cdh7/7.1.7/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976-bionic.parcel.sha256
        dest: /opt/cloudera/parcel-repo/
        mode: '0644'
      tags:
        - parcel.sha256

    - name: Download manifest json
      get_url:
        url: https://archive.cloudera.com/cdh7/7.1.7/parcels/manifest.json
        dest: /opt/cloudera/parcel-repo/
        mode: '0644'
      tags:
        - manifest