---
- name: Set shared buffer
  hosts: all
  become: yes
  tasks:


    - name: set shared buffer
      replace:
        path: /etc/postgresql/10/main/postgresql.conf
        regexp: '128'
        replace: "256"
        backup: yes

     
    - name: Enable service postgresql, and restart
      service:
        name: postgresql
        enabled: yes
        state: restarted
      tags:
        - start_at_boot

    - name: set shared buffer
      shell: sed -i '90s/peer/md5/' /etc/postgresql/10/main/pg_hba.conf
      tags:
        - "md5"
