
---
- name: Create databases and users
  hosts: all
  become: yes
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: set standard_conforming_strings=off
      community.postgresql.postgresql_set:
        name: standard_conforming_strings
        value: off
        db: "{{ item }}" 
      loop:
        - hive
        - oozie
      tags:
        - standard_conf_str
      

#    - name: Set confirming string off
#      postgresql_query:#
 #       query: ALTER DATABASE {{ item.db }} SET standard_conforming_strings=off
 #       db: "{{ item.db }}"
 #       login_user: "{{ item.user }}"
 #       login_password: "{{ item.passwd }}"
 #     with_items:
 #       - { db: hive, user: hive, passwd: admin } 
 #       - { db: oozie, user: oozie, passwd: admin } 
 #     tags:
 #       - confirmingstring     